name: Setup Repo

on:
  push:
    paths:
      - 'environments/**'

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terragrunt
        uses: gruntwork-io/terragrunt-action@v2
        with:
          terraform_version: 1.5.0
          terragrunt_version: 0.50.0

      - name: Debug GitHub Token
        run: |
          if [[ -z "${{ secrets.G_TOKEN }}" ]]; then 
            echo "G_TOKEN is EMPTY or NOT SET!";
          else 
            echo "G_TOKEN is SET, length: $(echo -n ${{ secrets.G_TOKEN }} | wc -c)";
          fi

      - name: Terragrunt Init
        run: terragrunt init
        working-directory: environments/dev

      - name: Terragrunt Plan
        run: terragrunt plan
        working-directory: environments/dev

      - name: Terragrunt Apply
        run: terragrunt apply -auto-approve
        working-directory: environments/dev
        env:
          G_TOKEN: ${{ secrets.G_TOKEN }}